version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: app
    container_name: app
    restart: unless-stopped
    ports:
      - 80:3000
    networks:
      - app
networks:
  app:
    driver: bridge